### ISSUE TITLE
License for the repo

### ISSUE THREAD

**Issue by WilfredAlmeida** [metaplex-foundation/das-api-testing#1]
Hello, thank you for putting this tool together and I'm keen on trying it out. 

I have noticed that the repository currently does not have a license specified. Adding a license to the project can help clarify the terms under which the code is shared, making it more accessible and usable for others.

Would you consider adding a license to the repository?

**Comment by StanChe** [comment]
Thanks for bringing it up Wilfred. We believe AGPLv3 should serve the community well. The license is added to the repository.

**Comment by WilfredAlmeida** [comment]
Thanks!
